apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-kit-admin
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: sandbox-kit-admin
  replicas: 1
  template:
    metadata:
      labels:
        app: sandbox-kit-admin
    spec:
      containers:
        - name: admin
          image: {{ .Values.containerImage }}
          imagePullPolicy: IfNotPresent
          command:
            - ksk
            - admin
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
            limits:
              cpu: "250m"
          envFrom:
            - secretRef:
                name: sandbox-kit

      serviceAccountName: sandbox-kit-admin


---

kind: Service
apiVersion: v1
metadata:
  name: admin
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: sandbox-kit-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080