apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-kit-reg
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: registration
  replicas: 1
  template:
    metadata:
      labels:
        app: registration
    spec:
      containers:
        - name: registration
          image: {{ .Values.containerImage }}
          imagePullPolicy: Always
          command:
            - ksk
            - registration
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "100m"
          env:
            - name: KSK_INSTRUCTIONSPATH
              value: /ksk/instructions.yaml
          volumeMounts:
            - name: config
              mountPath: /ksk/instructions.yaml
              subPath: instructions.yaml
      serviceAccountName: sandbox-kit-admin
      imagePullSecrets:
        - name: gitlab-registry
      volumes:
        - name: config
          configMap:
            name: instructions
            items:
              - key: yaml
                path: instructions.yaml

---

kind: Service
apiVersion: v1
metadata:
  name: reg
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: registration
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080