apiVersion: v1
kind: Secret
metadata:
  name: sandbox-kit
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  KSK_ADMIN_TOKEN: {{ .Values.adminToken | b64enc }}
  KSK_KUBERNETES_API_URI: {{ .Values.kubernetes.apiUri | b64enc }}
  KSK_KUBERNETES_API_CA: {{ .Values.kubernetes.apiCA | b64enc }}