apiVersion: v1
kind: Secret
metadata:
  name: sandbox-kit
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  KSK_ADMINTOKEN: {{ .Values.adminToken | b64enc }}
  KSK_KUBERNETES.APIURI: {{ .Values.kubernetes.apiUri | b64enc }}
  KSK_KUBERNETES.APICA: {{ .Values.kubernetes.apiCA | b64enc }}